In [9]:
import torch
import numpy as np

torch.cuda.is_available()


True

In [45]:
t1 =torch.tensor([[1,2,3],[1,2,3],
                 [1,2,3],
                 [1,2,3]])
t2 =torch.tensor([[1,2,3],
                [1,5,3],
                 [1,6,7],
                 [-3,2,3]])
t3 =torch.tensor([[1,-2,3],
                [1,0,3],
                 [1,1,9],
                 [-3,2,3]])

t1+t2

tensor([[ 2,  4,  6],
        [ 2,  7,  6],
        [ 2,  8, 10],
        [-2,  4,  6]])

In [46]:
def flatten(t):
    t = t.reshape(1,-1)
    t = t.squeeze()
    return t

In [47]:
flatten(t1)

tensor([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [48]:
t1.reshape(1,-1)[0]

tensor([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [49]:
t = torch.cat((t1,t2))
t.shape

torch.Size([8, 3])

In [56]:
t = torch.stack((t1,t2,t3))
t

tensor([[[ 1,  2,  3],
         [ 1,  2,  3],
         [ 1,  2,  3],
         [ 1,  2,  3]],

        [[ 1,  2,  3],
         [ 1,  5,  3],
         [ 1,  6,  7],
         [-3,  2,  3]],

        [[ 1, -2,  3],
         [ 1,  0,  3],
         [ 1,  1,  9],
         [-3,  2,  3]]])

In [72]:
t.reshape(3,12)

tensor([[ 1,  2,  3,  1,  2,  3,  1,  2,  3,  1,  2,  3],
        [ 1,  2,  3,  1,  5,  3,  1,  6,  7, -3,  2,  3],
        [ 1, -2,  3,  1,  0,  3,  1,  1,  9, -3,  2,  3]])

In [71]:
t.flatten(start_dim=1)

tensor([[ 1,  2,  3,  1,  2,  3,  1,  2,  3,  1,  2,  3],
        [ 1,  2,  3,  1,  5,  3,  1,  6,  7, -3,  2,  3],
        [ 1, -2,  3,  1,  0,  3,  1,  1,  9, -3,  2,  3]])